// lib/country-codes.ts
// ISO 3166-1 alpha-2 ↔ display name mapping
// react-svg-worldmap uses lowercase alpha-2 codes like "fr", "de", "cn"

export const ALPHA2_TO_NAME: Record<string, string> = {
  af: 'Afghanistan', al: 'Albania', dz: 'Algeria', ao: 'Angola', ar: 'Argentina',
  am: 'Armenia', au: 'Australia', at: 'Austria', az: 'Azerbaijan', bh: 'Bahrain',
  bd: 'Bangladesh', by: 'Belarus', be: 'Belgium', bj: 'Benin', bt: 'Bhutan',
  bo: 'Bolivia', ba: 'Bosnia', bw: 'Botswana', br: 'Brazil', bg: 'Bulgaria',
  bf: 'Burkina Faso', bi: 'Burundi', kh: 'Cambodia', cm: 'Cameroon', ca: 'Canada',
  cf: 'C.African Rep.', td: 'Chad', cl: 'Chile', cn: 'China', co: 'Colombia',
  cd: 'DR Congo', cg: 'Congo', cr: 'Costa Rica', hr: 'Croatia', cu: 'Cuba',
  cy: 'Cyprus', cz: 'Czech Rep.', dk: 'Denmark', dj: 'Djibouti', ec: 'Ecuador',
  eg: 'Egypt', sv: 'El Salvador', er: 'Eritrea', ee: 'Estonia', et: 'Ethiopia',
  fi: 'Finland', fr: 'France', ga: 'Gabon', de: 'Germany', gh: 'Ghana',
  gr: 'Greece', gt: 'Guatemala', gn: 'Guinea', ht: 'Haiti', hn: 'Honduras',
  hu: 'Hungary', in: 'India', id: 'Indonesia', ir: 'Iran', iq: 'Iraq',
  ie: 'Ireland', il: 'Israel', it: 'Italy', jm: 'Jamaica', jp: 'Japan',
  jo: 'Jordan', kz: 'Kazakhstan', ke: 'Kenya', kp: 'North Korea', kr: 'South Korea',
  kw: 'Kuwait', kg: 'Kyrgyzstan', la: 'Laos', lv: 'Latvia', lb: 'Lebanon',
  lr: 'Liberia', ly: 'Libya', lt: 'Lithuania', lu: 'Luxembourg', mg: 'Madagascar',
  mw: 'Malawi', my: 'Malaysia', ml: 'Mali', mr: 'Mauritania', mx: 'Mexico',
  md: 'Moldova', mn: 'Mongolia', ma: 'Morocco', mz: 'Mozambique', mm: 'Myanmar',
  na: 'Namibia', np: 'Nepal', nl: 'Netherlands', nz: 'New Zealand', ni: 'Nicaragua',
  ne: 'Niger', ng: 'Nigeria', mk: 'North Macedonia', no: 'Norway', om: 'Oman',
  pk: 'Pakistan', pa: 'Panama', py: 'Paraguay', pe: 'Peru', ph: 'Philippines',
  pl: 'Poland', pt: 'Portugal', qa: 'Qatar', ro: 'Romania', ru: 'Russia',
  rw: 'Rwanda', sa: 'Saudi Arabia', sn: 'Senegal', rs: 'Serbia', sl: 'Sierra Leone',
  so: 'Somalia', za: 'South Africa', ss: 'South Sudan', es: 'Spain', lk: 'Sri Lanka',
  sd: 'Sudan', se: 'Sweden', ch: 'Switzerland', sy: 'Syria', tw: 'Taiwan',
  tj: 'Tajikistan', tz: 'Tanzania', th: 'Thailand', tg: 'Togo', tn: 'Tunisia',
  tr: 'Turkey', tm: 'Turkmenistan', ug: 'Uganda', ua: 'Ukraine', ae: 'UAE',
  gb: 'United Kingdom', us: 'United States', uy: 'Uruguay', uz: 'Uzbekistan',
  ve: 'Venezuela', vn: 'Vietnam', ye: 'Yemen', zm: 'Zambia', zw: 'Zimbabwe',
}

export const NAME_TO_ALPHA2: Record<string, string> = Object.fromEntries(
  Object.entries(ALPHA2_TO_NAME).map(([k, v]) => [v, k])
)

// Land border adjacency — key country borders all values
export const NEIGHBORS: Record<string, string[]> = {
  // Western Europe
  fr: ['es', 'be', 'lu', 'de', 'ch', 'it'],
  es: ['fr', 'pt', 'ma'],
  pt: ['es'],
  be: ['fr', 'lu', 'nl', 'de'],
  nl: ['be', 'de'],
  lu: ['fr', 'be', 'de'],
  de: ['fr', 'be', 'nl', 'lu', 'ch', 'at', 'cz', 'pl', 'dk'],
  ch: ['fr', 'de', 'at', 'it'],
  at: ['de', 'ch', 'it', 'si', 'sk', 'hu', 'cz'],
  it: ['fr', 'ch', 'at', 'si'],
  dk: ['de'],
  no: ['se', 'fi', 'ru'],
  se: ['no', 'fi'],
  fi: ['no', 'se', 'ru'],
  ie: ['gb'],
  gb: ['ie', 'fr'],
  // Eastern Europe
  pl: ['de', 'cz', 'sk', 'ua', 'by', 'lt', 'ru'],
  cz: ['de', 'at', 'sk', 'pl'],
  sk: ['cz', 'at', 'hu', 'pl', 'ua'],
  hu: ['at', 'sk', 'ro', 'rs', 'hr', 'si', 'ua'],
  ro: ['hu', 'md', 'ua', 'bg', 'rs'],
  bg: ['ro', 'rs', 'mk', 'gr', 'tr'],
  rs: ['hu', 'ro', 'bg', 'mk', 'ba', 'hr', 'me', 'al'],
  hr: ['si', 'hu', 'rs', 'ba'],
  ba: ['hr', 'rs', 'me'],
  si: ['it', 'at', 'hu', 'hr'],
  mk: ['rs', 'bg', 'gr', 'al'],
  al: ['rs', 'mk', 'gr'],
  gr: ['al', 'mk', 'bg', 'tr'],
  ua: ['ro', 'md', 'hu', 'sk', 'pl', 'by', 'ru'],
  md: ['ro', 'ua'],
  by: ['pl', 'lt', 'lv', 'ua', 'ru'],
  lt: ['pl', 'by', 'lv'],
  lv: ['lt', 'ee', 'by', 'ru'],
  ee: ['lv', 'ru'],
  ru: ['no', 'fi', 'ee', 'lv', 'lt', 'pl', 'by', 'ua', 'ge', 'az', 'kz', 'cn', 'mn', 'kp'],
  // Caucasus
  ge: ['ru', 'tr', 'am', 'az'],
  am: ['ge', 'tr', 'az', 'ir'],
  az: ['ge', 'am', 'ru', 'ir', 'tr'],
  // Middle East
  tr: ['ge', 'am', 'az', 'ir', 'iq', 'sy', 'gr', 'bg'],
  sy: ['tr', 'lb', 'il', 'jo', 'iq'],
  lb: ['sy', 'il'],
  il: ['lb', 'sy', 'jo', 'eg'],
  jo: ['il', 'sy', 'iq', 'sa'],
  iq: ['tr', 'sy', 'jo', 'sa', 'kw', 'ir'],
  ir: ['tr', 'am', 'az', 'tm', 'af', 'pk', 'iq'],
  kw: ['iq', 'sa'],
  sa: ['jo', 'iq', 'kw', 'ae', 'om', 'ye'],
  ae: ['sa', 'om'],
  om: ['ae', 'sa', 'ye'],
  ye: ['sa', 'om'],
  qa: ['sa'],
  // Central Asia
  kz: ['ru', 'cn', 'kg', 'uz', 'tm'],
  uz: ['kz', 'kg', 'tj', 'af', 'tm'],
  tm: ['kz', 'uz', 'af', 'ir'],
  kg: ['kz', 'cn', 'tj', 'uz'],
  tj: ['kg', 'cn', 'af', 'uz'],
  af: ['tm', 'uz', 'tj', 'cn', 'pk', 'ir'],
  // South Asia
  pk: ['ir', 'af', 'cn', 'in'],
  in: ['pk', 'cn', 'np', 'bt', 'bd', 'mm'],
  np: ['in', 'cn'],
  bt: ['in', 'cn'],
  bd: ['in', 'mm'],
  lk: ['in'],
  mm: ['in', 'bd', 'cn', 'la', 'th'],
  // Southeast Asia
  th: ['mm', 'la', 'kh', 'my'],
  la: ['mm', 'cn', 'vn', 'kh', 'th'],
  vn: ['cn', 'la', 'kh'],
  kh: ['th', 'la', 'vn'],
  my: ['th', 'id'],
  id: ['my', 'pg'],
  ph: ['my'],
  pg: ['id', 'au'],
  // East Asia
  cn: ['ru', 'mn', 'kz', 'kg', 'tj', 'af', 'pk', 'in', 'np', 'bt', 'mm', 'la', 'vn', 'kp'],
  mn: ['ru', 'cn'],
  kp: ['ru', 'cn', 'kr'],
  kr: ['kp'],
  jp: ['kr'],
  // Africa
  eg: ['il', 'ly', 'sd'],
  ly: ['eg', 'tn', 'dz', 'ne', 'td', 'sd'],
  tn: ['ly', 'dz'],
  dz: ['tn', 'ly', 'ne', 'ml', 'mr', 'ma'],
  ma: ['dz', 'es'],
  mr: ['dz', 'ml', 'sn'],
  ml: ['dz', 'ne', 'bf', 'gn', 'sn', 'mr'],
  ne: ['ly', 'dz', 'ml', 'bf', 'ng', 'td'],
  td: ['ly', 'ne', 'ng', 'cm', 'cf', 'sd'],
  sd: ['eg', 'ly', 'td', 'cf', 'ss', 'et', 'er'],
  ss: ['sd', 'et', 'ke', 'ug', 'cd', 'cf'],
  et: ['er', 'dj', 'so', 'ke', 'ss', 'sd'],
  er: ['et', 'dj', 'sd'],
  dj: ['er', 'et', 'so'],
  so: ['dj', 'et', 'ke'],
  ke: ['et', 'so', 'ug', 'tz', 'ss'],
  ug: ['ss', 'ke', 'tz', 'rw', 'bi', 'cd'],
  tz: ['ke', 'ug', 'rw', 'bi', 'mw', 'zm', 'mz', 'cd'],
  rw: ['ug', 'tz', 'bi', 'cd'],
  bi: ['rw', 'cd', 'tz'],
  cd: ['cf', 'ss', 'ug', 'rw', 'bi', 'tz', 'zm', 'ao', 'cg'],
  cg: ['cm', 'cf', 'cd', 'ga', 'ao'],
  cf: ['td', 'sd', 'ss', 'cd', 'cg', 'cm'],
  cm: ['ng', 'td', 'cf', 'cg', 'ga'],
  ng: ['ne', 'td', 'cm', 'bj'],
  bj: ['ng', 'bf', 'tg', 'ne'],
  tg: ['bj', 'gh', 'bf'],
  gh: ['tg', 'ci', 'bf'],
  bf: ['ml', 'ne', 'bj', 'tg', 'gh', 'ci'],
  ci: ['bf', 'ml', 'gn', 'lr', 'gh'],
  gn: ['ml', 'sl', 'lr', 'ci', 'sn'],
  sl: ['gn', 'lr'],
  lr: ['sl', 'gn', 'ci'],
  sn: ['mr', 'ml', 'gn'],
  ga: ['cm', 'cg', 'ao'],
  ao: ['ga', 'cg', 'cd', 'na', 'zm'],
  na: ['ao', 'zm', 'bw', 'za'],
  zm: ['ao', 'cd', 'tz', 'mw', 'mz', 'zw', 'bw', 'na'],
  zw: ['zm', 'bw', 'mz', 'za'],
  bw: ['na', 'zm', 'zw', 'za'],
  mz: ['tz', 'zm', 'mw', 'zw', 'za'],
  mw: ['tz', 'zm', 'mz'],
  za: ['na', 'bw', 'zw', 'mz'],
  mg: ['mz'],
  // Americas
  us: ['ca', 'mx'],
  ca: ['us'],
  mx: ['us', 'gt'],
  gt: ['mx', 'bz', 'hn', 'sv'],
  bz: ['mx', 'gt'],
  hn: ['gt', 'sv', 'ni'],
  sv: ['gt', 'hn'],
  ni: ['hn', 'cr'],
  cr: ['ni', 'pa'],
  pa: ['cr', 'co'],
  co: ['pa', 've', 'br', 'pe', 'ec'],
  ec: ['co', 'pe'],
  ve: ['co', 'br', 'gy'],
  gy: ['ve', 'br', 'sr'],
  sr: ['gy', 'br'],
  br: ['ve', 'gy', 'sr', 'bo', 'pe', 'co', 'ar', 'uy', 'py'],
  pe: ['ec', 'co', 'br', 'bo', 'cl'],
  bo: ['br', 'pe', 'cl', 'ar', 'py'],
  cl: ['pe', 'bo', 'ar'],
  ar: ['cl', 'bo', 'br', 'py', 'uy'],
  py: ['br', 'bo', 'ar'],
  uy: ['br', 'ar'],
}
